orochi-network/zkDatabase

specs/README.md

Added specification for data collection

Added specification for data collection

---

specs/README.md

Update data collection spec

---

.github/workflows/node.js.yml
zkdb/package.json

Misc/update GitHub action to check code build

---

.github/workflows/node.js.yml

Update Github action to build npm package

---

zkdb/src/examples/zk-database-storage.ts

Update ZK Database Storage example

---

zkdb/src/storage-engine/ipfs.ts

Change listen address to loopback and remove bootstrap nodes

---

packages/portal/package-lock.json
packages/portal/package.json

Bug: Fix .git not found when run npm install in portal folder

---

examples/src/Add.test.ts
examples/src/Add.ts
examples/src/interact.ts
examples/src/piglet-bank.ts
examples/src/zk-database-storage.ts
packages/portal/README.md
packages/portal/src/apollo/app/merkle-tree.ts
packages/zkdb/.eslintrc.cjs
packages/zkdb/README.md
packages/zkdb/jest-resolver.cjs
packages/zkdb/jest.config.js
packages/zkdb/package-lock.json
packages/zkdb/package.json
packages/zkdb/src/core/common.ts
packages/zkdb/src/core/schema.ts
packages/zkdb/src/core/zkdb-contract.ts
packages/zkdb/src/core/zkdb-storage.ts
packages/zkdb/src/examples/piglet-bank.ts
packages/zkdb/src/examples/zk-database-storage.ts
packages/zkdb/src/merkle-tree/common.ts
packages/zkdb/src/merkle-tree/merkle-tree-base.ts
packages/zkdb/src/merkle-tree/merkle-tree-extended.ts
packages/zkdb/src/merkle-tree/merkle-tree-storage.ts
packages/zkdb/src/merkle-tree/merkle-tree.test.ts
packages/zkdb/src/storage-engine/bson.test.ts
packages/zkdb/src/storage-engine/ipfs.ts
packages/zkdb/src/utilities/binary.ts

**Note:**  there are some changes that break the test so, jest not working.

Migrate from snarkyjs to o1js

---

packages/portal/package-lock.json
packages/portal/package.json
packages/portal/src/helper/response-error.ts

Audit libs

---

packages/zkdb/src/core/schema.ts
packages/zkdb/src/examples/piglet-bank.ts

- Updated the Schema.js file to properly handle the public-keys serialization.
- Updated the piglet_bank.ts example to use public-keys.

fix serializer bug

---

packages/kubo/jest.config.js
packages/kubo/package-lock.json
packages/kubo/package.json
packages/kubo/src/index.ts
packages/kubo/tests/kubo-client.test.ts
packages/kubo/tsconfig.json

Added read and write stream to the KuboClient

Added streaming feature to the kubo

---

packages/zkdb/.prettierrc
packages/zkdb/package-lock.json
packages/zkdb/package.json
packages/zkdb/src/utilities/deserialize.ts
packages/zkdb/src/utilities/index.ts
packages/zkdb/src/utilities/serialize.ts

Add new feature to serialized and deserialized data make it cheaper to store.

Add new feature to serialize/deserialize data into

---

.github/workflows/publish-kubo.yml

Modify secret variable

---

packages/serverless/.eslintrc
packages/serverless/babel.config.cjs
packages/serverless/jest-resolver.cjs
packages/serverless/jest.config.mjs
packages/serverless/package-lock.json
packages/serverless/package.json
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/apollo/index.ts
packages/serverless/src/core/schema.ts
packages/serverless/src/helper/distributed-lock.ts
packages/serverless/src/helper/extended-merkle-witness.ts
packages/serverless/src/model/abstract/basic.ts
packages/serverless/src/model/abstract/database-engine.ts
packages/serverless/src/model/document.ts
packages/serverless/src/model/merkle-tree-metadata.ts
packages/serverless/src/model/merkle-tree-pool.ts
packages/serverless/src/model/merkle-tree.ts
packages/serverless/src/service/MerkleTreeService.ts
packages/serverless/src/service/SmartContractService.ts
packages/serverless/tsconfig.json

Building MerkeTree Service

---

package.json
packages/explorer/tsconfig.json
packages/kubo/tsconfig.json
packages/portal/package.json
packages/portal/tsconfig.json
packages/proof-service/tsconfig.json
packages/serverless/tsconfig.json
packages/storage/tsconfig.json
packages/zkdb/tsconfig.json
tsconfig.json
yarn.lock

- [] Feature
Fix mono repo setup with link dependencies
Thanks @chiro-hiro for giving me a hand making this PR.

Bug: Link dependencies in mono-repo

---

packages/serverless/.eslintrc
packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/apollo/app/database.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/group.ts
packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/apollo/app/metadata.ts
packages/serverless/src/apollo/app/user.ts
packages/serverless/src/apollo/index.ts
packages/serverless/src/helper/config.ts
packages/serverless/tsconfig.json
tsconfig.json

Fix type in resolver

---

.github/workflows/main.yml

Reorder npm access token preparation

---

packages/serverless/package.json
yarn.lock

Fix environment loader issue without .env

---

.dockerignore
.github/workflows/build-and-push-docker.yml
.gitignore
packages/broker-service/.env.example
packages/broker-service/Dockerfile
packages/ftp/Dockerfile
packages/proof-service/Dockerfile
packages/serverless/Dockerfile

Add new Dockerfile for mounting npm-token as secret when building images
Add new github action script for CI.

Add new Dockerfile with npm-token authen and CI script

---

packages/serverless/src/index.ts

Set Access-Control-Allow-Credentials to true

---

packages/api/package.json

Release 1.0.1 package @zkdb/api

---

packages/api/package.json
packages/broker-service/package.json
packages/ftp/.env.example
packages/ftp/package.json
packages/ftp/src/helper/config.ts
packages/kubo/package.json
packages/proof-service/package.json
packages/proof-service/src/api/client.ts
packages/proof-service/src/api/get-next-task.ts
packages/proof-service/src/domain/create-proof.ts
packages/proof-service/src/helper/config.ts
packages/proof-service/tsconfig.json
packages/serverless/package.json
packages/smart-contract/package.json
packages/storage/package.json
packages/website/package.json
packages/zkdb/package.json
yarn.lock

Release candidate version 1.1.0

---

packages/api/src/graphql/client.ts
packages/api/src/graphql/collection-index.ts
packages/api/src/graphql/collection.ts
packages/api/src/graphql/common.ts
packages/api/src/graphql/database.ts
packages/api/src/graphql/document.ts
packages/api/src/graphql/group.ts
packages/api/src/graphql/merkle.ts
packages/api/src/graphql/ownership.ts
packages/api/src/graphql/permission.ts
packages/api/src/graphql/proof.ts
packages/api/src/graphql/user.ts
packages/serverless/src/model/abstract/document.ts
yarn.lock

Release fix warning and missing packages

---

.github/workflows/main.yml

Bug: Add zkdb in publish list & fix npm registry authentication

---

packages/zkdb/package.json

Update zkdb package.json

---

packages/broker-service/package.json
packages/serverless/src/index.ts

Misc: Remove cookie config allow all cors

---

packages/api/package.json
packages/api/src/graphql/client.ts
packages/zkdb/package.json

Fix type issue that lead to unable to build

---

packages/serverless/src/apollo/app/user.ts
packages/serverless/src/index.ts

Feature: Fix credential and login problem 

---

.github/workflows/build-and-push-docker.yml
.github/workflows/main.yml

Swtich to use self host runner

---

package.json

Remove all build folder when run build at root

---

.github/workflows/main.yml
packages/proof-service/package.json
packages/serverless/package.json
packages/smart-contract/package.json
packages/storage/package.json
packages/zkdb/package.json

Disable test in our repo

---

packages/serverless/src/domain/use-case/ownership.ts
packages/serverless/src/index.ts

Bug: Fix cannot logout due to req is undefined 

---

packages/serverless/src/domain/use-case/user.ts

Bug: Fix change query find model user

---

examples/src/features/permissions.ts
packages/api/src/graphql/permission.ts
packages/api/src/graphql/types/ownership.ts
packages/serverless/src/domain/use-case/permission.ts
packages/zkdb/src/sdk/impl/collection.ts

Bug: fix permissions bug

---

examples/src/features/indexes.ts
packages/api/src/graphql/collection-index.ts
packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/domain/use-case/collection.ts

Bug: fix indexes bug with grahpql fields, multi-document issue and proper

---

packages/serverless/src/apollo/app/types/collection.ts
packages/serverless/src/domain/types/collection.ts
packages/serverless/src/domain/use-case/collection.ts
packages/storage/src/database/database-engine.ts
packages/storage/src/database/general/collection.ts

Expose collection size

---

packages/serverless/src/apollo/app/user.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/user.ts
packages/serverless/src/helper/common.ts
packages/serverless/src/helper/jwt.ts
packages/serverless/src/model/global/user.ts
packages/serverless/tsconfig.json

Feature: Add search find user query

---

packages/serverless/src/domain/use-case/user.ts
packages/serverless/src/model/database/user-group.ts

Bug: Fix user existed check

---

packages/api/src/graphql/database.ts
packages/api/src/graphql/document.ts
packages/api/src/graphql/types/pagination.ts
packages/api/src/graphql/user.ts
packages/serverless/src/apollo/app/database.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/user.ts
packages/serverless/src/domain/types/pagination.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/user.ts
packages/serverless/src/model/abstract/document.ts
packages/serverless/src/model/global/user.ts
packages/storage/src/database/common/setting.ts

Return Pagination Metadata

---

packages/zkdb/src/sdk/impl/database.ts
packages/zkdb/src/sdk/impl/group.ts
packages/zkdb/src/types/group.ts

Bug: Fix group naming

---

.github/workflows/build-and-push-docker.yml

Changes logic for Github action to detect changes between 2 last merge instead of two last commit. Also, I use an unified step to build and push changed packages instead of separating it. 
Moreover, I add a step to make changes and push to GitOps repo for faster deployment in test environment.

Change logic Github Action for new CI/CD flow

---

.github/workflows/build-and-push-docker.yml

Add lacking env.version lead to failed push to Dockerhub

Add lacking env.version

---

.github/workflows/build-and-push-docker.yml

Fix deprecated function in Github Action

Fix deprecated function in Github Action

---

packages/serverless/src/apollo/app/collection-index.ts

Misc: Remove unnecessary tx for reading and single operation

---

packages/serverless/src/apollo/app/merkle-tree.ts

Bug: Remove tx and root in getWitness

---

packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/domain/use-case/collection.ts
packages/storage/src/database/general/database.ts

Misc: Remove catch block that session tx will handle

---

packages/api/src/graphql/database.ts
packages/api/src/graphql/document.ts
packages/api/src/graphql/user.ts
packages/api/src/index.ts
packages/proof-service/src/domain/create-proof.ts
packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/domain/types/merkle-tree.ts
packages/serverless/src/domain/use-case/merkle-tree.ts
packages/storage/src/database/common/merkle-tree.ts
packages/zkdb/src/index.ts

Feature: Request Merkle Tree Nodes by Level

---

.github/workflows/build-and-push-docker.yml

Changes to use env for building docker

Bug: Invalid service name when build image

---

.github/workflows/build-and-push-docker.yml

Add skipping push to gitops step

Devops: Add skipping push to gitops step

---

packages/api/package.json

Misc: Update patch version for zkdb api

---

packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/domain/types/collection-index.ts
packages/serverless/src/domain/use-case/collection.ts
packages/storage/src/database/common/merkle-tree.ts
packages/storage/src/database/general/collection.ts

Read collection index description

---

packages/zkdb/package.json
yarn.lock

Misc: Unused import cause build error

---

examples/src/features/indexes.ts
examples/src/features/permissions.ts
examples/src/features/save-documents.ts
packages/api/src/graphql/collection.ts
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/domain/types/schema.ts
packages/serverless/src/domain/use-case/collection-metadata.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/schema.ts
packages/storage/src/database/general/database.ts
packages/zkdb/src/sdk/impl/database.ts
packages/zkdb/src/sdk/interfaces/database.ts
packages/zkdb/src/sdk/schema.ts

enable the creation of indexes during the collection creation process

---

packages/serverless/src/domain/use-case/collection.ts
packages/smart-contract/package.json
packages/smart-contract/src/contracts/zkdb-app.ts

Misc: Pump patch version for publish

---

packages/api/src/graphql/collection.ts
packages/serverless/src/apollo/app/collection.ts

Bug: Fix collectionCreate force create index first problem

---

packages/smart-contract/package.json
packages/smart-contract/rollup.config.js

[plugin:vite:import-analysis] Failed to resolve entry for package "@zkdb/smart-contract". The package may have incorrect main/module/exports specified in its package.json.

Misc: Rename name output umd

---

packages/smart-contract/src/cache/cache-manager.ts
packages/smart-contract/src/helper/environment.ts

Cache for browser is not supported

---

packages/smart-contract/package.json
packages/smart-contract/rollup.config.js

Bug: Fix mapping esm cjs in package.json and remove umd

---

.github/workflows/build-and-push-docker.yml

Change logic to detect changes and build. Keep detecting changes, but I will build all the services for not to miss changes when there's some hotfix commit.

Devops: Change logic for building images

---

packages/smart-contract/package.json
packages/smart-contract/rollup.config.js
packages/smart-contract/src/cache/cache-builder.ts
packages/smart-contract/src/cache/cache-downloader.ts
packages/smart-contract/src/cache/cache-manager.ts
packages/smart-contract/src/cache/ftp-downloader.ts
packages/smart-contract/src/helper/environment.ts

Feature: Implement dynamic node import

---

packages/serverless/src/apollo/app/collection.ts

Bug: Remove required indexes

---

packages/proof-service/src/api/client.ts
packages/serverless/src/domain/use-case/collection.ts
packages/smart-contract/package.json
packages/smart-contract/rollup.config.js
yarn.lock

Fix always got index not found problem due to the append _1 after corrected index name

Bug: Fix drop index not found

---

packages/api/src/graphql/client.ts

Fixed networkError: TypeError: Headers.append: "function (obj)

---

packages/broker-service/Dockerfile
packages/ftp/Dockerfile
packages/proof-service/Dockerfile
packages/serverless/Dockerfile

Remove chown step and put it in oneline for faster build

Remove chown step and put it in oneline for faster build

---

packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/domain/use-case/merkle-tree.ts
packages/storage/src/database/common/merkle-tree.ts

add getChildrenNodes and getWitnessPath

---

packages/serverless/src/apollo/app/database.ts
packages/serverless/src/domain/use-case/database.ts
packages/storage/src/database/database-engine.ts

Misc: Add throw error for database name

---

packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/domain/types/merkle-tree.ts
packages/serverless/src/domain/use-case/merkle-tree.ts
packages/storage/src/database/common/merkle-tree.ts

denote empty merkle nodes

---

packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/domain/types/proof-status.ts

combine document statuses to get a single one for the entire database

---

packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/domain/types/proof-status.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/database.ts

Fix: Filter nullable data from result

---

packages/proof-service/src/index.ts

Feature: Add on mainnet for proof service

---

packages/compile-service/src/helper/config.ts
packages/compile-service/src/helper/logger.ts
packages/compile-service/src/index.ts
packages/serverless/src/domain/use-case/database.ts

Feature: Add on config for compile service

---

packages/compile-service/.env.example
packages/compile-service/package.json

Feature: Adding env.example and start:prod script

---

packages/compile-service/package.json
packages/compile-service/tsconfig.json
tsconfig.json

Misc: Add to compile service workspace

---

packages/compile-service/src/helper/config.ts
packages/compile-service/src/index.ts
packages/compile-service/src/message-queue.ts
packages/serverless/src/helper/mq.ts

Feature: Adding url redis

---

packages/serverless/src/helper/mq.ts

Bug: Fixing config missing import 

---

packages/proof-service/src/domain/create-proof.ts

improve create proof logic

---

.github/workflows/build-and-push-docker.yml

Update CI/CD script for compile-service

Update CI/CD script for compile-service

---

packages/compile-service/Dockerfile

Add Dockerfile for compile-service

Add Dockerfile for compile-service

---

examples/src/features/indexes.ts
packages/api/src/graphql/collection-index.ts
packages/api/src/graphql/collection.ts
packages/api/src/graphql/types/collection-index.ts
packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/apollo/app/database.ts
packages/serverless/src/apollo/app/metadata.ts
packages/serverless/src/apollo/app/types/collection-index.ts
packages/serverless/src/apollo/app/types/collection.ts
packages/serverless/src/apollo/index.ts
packages/serverless/src/apollo/types/collection-index.ts
packages/serverless/src/apollo/types/sorting.ts
packages/serverless/src/domain/common/schema.ts
packages/serverless/src/domain/types/collection-index.ts
packages/serverless/src/domain/types/schema.ts
packages/serverless/src/domain/types/sorting.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/schema.ts
packages/serverless/src/model/database/collection-metadata.ts
packages/smart-contract/package.json
packages/zkdb/package.json
packages/zkdb/src/sdk/impl/collection.ts
packages/zkdb/src/sdk/impl/database.ts
packages/zkdb/src/sdk/interfaces/collection.ts
packages/zkdb/src/sdk/interfaces/database.ts
packages/zkdb/src/types/collection-index.ts

Reverts orochi-network/zkDatabase#226

Index sorting feature

---

packages/compile-service/src/service/zk-compile.ts
packages/serverless/src/domain/use-case/collection.ts

Misc: Remove hardcode indexName

---

packages/compile-service/src/helper/config.ts
packages/compile-service/src/index.ts
packages/compile-service/src/message-queue.ts
packages/compile-service/src/service/zk-compile.ts
packages/proof-service/src/api/client.ts
packages/proof-service/src/index.ts
packages/serverless/src/apollo/app/database.ts
packages/serverless/src/apollo/app/user.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/user.ts
packages/serverless/src/helper/mq.ts

Feature: Handle queue failed 

---

packages/smart-contract/src/contracts/zkdb-app.ts

add some security features to zkapp

---

packages/smart-contract/src/contracts/zkdb-app.ts

Bug: Update_not_permitted_permissions

---

packages/smart-contract/src/contracts/zkdb-app.ts

Bug: Remove provedState checking as it does not work

---

packages/serverless/Dockerfile

update Dockerfile to build @zkdb/smart-contract before @zkdb/storage

Devops: Update Dockerfile to build @zkdb/smart-contract before @zkdb/storage

---

packages/serverless/src/helper/config.ts
packages/serverless/src/index.ts

Feature: Refactor mina network config

---

packages/serverless/src/apollo/app/document.ts
packages/serverless/src/domain/use-case/document.ts

Bug: Fix separate transaction bug

---

packages/smart-contract/jest-resolver.cjs
packages/smart-contract/jest.config.js
packages/smart-contract/package.json
yarn.lock

Update new version of Jest and update its configuration as well, fix the script path in `package.json`

Bug: Fix jest and ESM incompatible issue for smart contract package

---

packages/smart-contract/src/contracts/zkdb-app.ts
packages/smart-contract/src/proof/proof-program.ts

Bug: Fix incorrect state check

---

packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/apollo/app/transaction.ts
packages/serverless/src/apollo/app/types/transaction.ts
packages/serverless/src/domain/types/transaction.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/storage/src/database/common/transactions.ts

Bug: Fix bug empty rollup list

---

packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/prover.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/storage/src/database/index.ts
packages/storage/src/database/transaction/compound-transaction-manager.ts

Feture: Compound Transaction

---

packages/compile-service/src/index.ts

Bug: Check tx periodically in compile service

---

packages/serverless/src/apollo/app/rollup.ts

Bug; Rename txHash to transactionHash

---

packages/serverless/src/domain/use-case/database.ts

Feature: Deploy status is not updated

---

packages/smart-contract/test/proof/proot.test.ts

add test that cover all cases for proof generation

---

packages/smart-contract/src/network/index.ts
packages/smart-contract/src/network/native_api.ts
packages/zkdb/src/sdk/signer/browser-signer.ts
packages/zkdb/src/sdk/signer/interface/signer.ts
packages/zkdb/src/sdk/signer/nodejs-signer.ts
packages/zkdb/src/types/transaction-params.ts

implement signAndSendTransaction request

---

packages/serverless/src/domain/use-case/rollup.ts
packages/storage/src/database/common/rollup-history.ts
packages/storage/src/database/global/proof.ts

Bug: Wrong status

---

packages/api/package.json
packages/api/src/graphql/client.ts
packages/api/src/graphql/environment.ts
packages/api/src/graphql/types/environment.ts
packages/serverless/src/apollo/app/environment.ts
packages/serverless/src/apollo/index.ts
packages/zkdb/package.json

Feature: Implement get config environment

---

packages/zkdb/package.json

Misc: Pump api version for zkdb sdk and api

---

packages/serverless/src/apollo/app/environment.ts
packages/zkdb/package.json

Bug: Fix wrong import from environment

---

packages/api/src/graphql/client.ts
packages/zkdb/package.json
packages/zkdb/src/sdk/global/zkdatabase-client.ts
packages/zkdb/src/utils/environment.ts

Bug: Fix api url wrong format in zkdatabase client connect method

---

packages/api/package.json
packages/zkdb/package.json

Misc: Pump api patch version

---

packages/api/package.json
yarn.lock

Misc: Return zkdb back to previous version

---

.github/workflows/main.yml

Remove build at root folder

---

.github/workflows/main.yml

Add a command to build storage package

---

packages/zkdb/package.json
yarn.lock

Misc: Pump api version for zkdb

---

package.json

Fix yarn build process with workspace order

---

examples/package.json
examples/src/features/transfer-owner-database.ts
examples/src/utils/config.ts
packages/api/package.json
packages/api/src/graphql/database.ts
packages/api/src/graphql/types/database.ts
packages/api/src/graphql/user.ts
packages/serverless/src/apollo/app/database.ts
packages/serverless/src/domain/use-case/database.ts
packages/smart-contract/src/cache/cache-builder.ts
packages/zkdb/src/sdk/impl/system.ts
packages/zkdb/src/sdk/interfaces/collection.ts
packages/zkdb/src/sdk/interfaces/system.ts
packages/zkdb/src/types/database.ts
packages/zkdb/src/types/user.ts

Feature: Add on check user exist

---

packages/permission/.gitattributes
packages/permission/.gitignore
packages/permission/.npmignore
packages/permission/.prettierignore
packages/permission/.prettierrc
packages/permission/LICENSE
packages/permission/README.md
packages/permission/babel.config.cjs
packages/permission/config.json
packages/permission/eslint.config.js
packages/permission/jest-resolver.cjs
packages/permission/jest.config.js
packages/permission/package.json
packages/permission/rollup.config.js
packages/permission/src/common.ts
packages/permission/src/index.ts
packages/permission/src/permission-base.ts
packages/permission/src/permission.ts
packages/permission/tsconfig.json
packages/permission/typedoc.json

Add new permission class and permission package

---

.github/workflows/main.yml

Fix invalid yarn command

---

packages/serverless/src/apollo/app/database.ts
packages/serverless/src/common/const.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/group.ts
packages/serverless/src/domain/use-case/transaction.ts

Feature: Add transaction and default group admin

---

packages/compile-service/src/index.ts
packages/compile-service/src/service/zk-compile.ts

Ensure a single transaction per time

---

packages/permission/package.json
packages/permission/src/index.ts

Export `PermissionDetailPartial` in `@zkdb/permission`

Feature: export `PermissionDetailPartial` in `@zkdb/permission`

---

.github/workflows/main.yml

Add token to install package

---

packages/permission/package.json
packages/permission/rollup.config.js
yarn.lock

Improve import alias in permission package

Improve import alias in permission package

---

packages/permission/package.json
packages/permission/src/common.ts

Fix wrong typ for permission and ownership

---

packages/serverless/package.json
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/types/collection.ts

Feature: Refactor collection serverless

---

packages/serverless/Dockerfile

Fix Dockerfile in serverless service

---

packages/serverless/src/apollo/app/document.ts

Refactor: fix types in apollo document resolver

---

packages/serverless/src/types/metadata.ts
packages/serverless/src/types/proof.ts
packages/serverless/src/types/rollup.ts
packages/serverless/src/types/transaction.ts

Update type for and import

---

packages/common/package.json
packages/common/src/schema.ts
packages/common/src/types/collection.ts
packages/common/src/types/common.ts
packages/common/src/types/database.ts
packages/common/src/types/document.ts
packages/common/src/types/metadata.ts
packages/common/src/types/ownership.ts
packages/common/src/types/schema.ts

Bug: Refactor schema index collection metadata

---

packages/common/src/types/collection.ts
packages/common/src/types/database.ts
packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/domain/use-case/collection-metadata.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/metadata.ts
packages/serverless/src/domain/use-case/transaction.ts
packages/serverless/src/helper/common.ts
packages/serverless/src/model/database/metadata-collection.ts
packages/storage/src/database/base/general.ts

Bug: Refactor collection serverless

---

packages/common/src/types/group.ts
packages/serverless/src/apollo/app/group.ts
packages/serverless/src/domain/use-case/group.ts
packages/serverless/src/model/database/group.ts
packages/serverless/src/model/database/user-group.ts

Refactor group endpoint

---

packages/common/src/types/document.ts
packages/common/src/types/metadata.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/domain/use-case/document-history.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/model/abstract/document.ts

Refactor document history and document related resolvers

---

packages/common/src/types/sequencer.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/prover.ts
packages/storage/src/database/common/sequencer.ts

Bug: Fix sequencer

---

packages/broker-service/Dockerfile
packages/compile-service/Dockerfile
packages/ftp/Dockerfile
packages/proof-service/Dockerfile
packages/serverless/Dockerfile

Refactor Dockerfiles to use specific user and group IDs for non-root user creation

Refactor Dockerfiles to use specific user and group IDs for non-root user creation

---

packages/api/src/graphql/client.ts
packages/api/src/graphql/collection-index.ts
packages/api/src/graphql/collection.ts
packages/api/src/graphql/database.ts
packages/api/src/graphql/document.ts
packages/api/src/graphql/environment.ts
packages/api/src/graphql/group.ts
packages/api/src/graphql/index.ts
packages/api/src/graphql/merkle.ts
packages/api/src/graphql/metadata.ts
packages/api/src/graphql/ownership.ts
packages/api/src/graphql/permission.ts
packages/api/src/graphql/proof.ts
packages/api/src/graphql/rollup.ts
packages/api/src/graphql/user.ts
packages/api/src/utils/environment.ts
packages/api/tsconfig.json
packages/common/src/types/document.ts
packages/common/src/types/environment.ts
packages/common/src/types/index.ts
packages/common/src/types/metadata.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/metadata.ts
packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/domain/use-case/document-history.ts
packages/serverless/src/domain/use-case/ownership.ts

Bug: Refactor typing for api and add metadata

---

packages/compile-service/Dockerfile

Fix compile service Dockerfile

---

packages/common/src/types/document.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/metadata.ts
packages/serverless/src/domain/use-case/document-history.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/model/abstract/document.ts
packages/storage/src/database/transaction/transaction-manager.ts

Refactor document related code

---

packages/common/src/types/collection.ts
packages/common/src/validation/index.ts
packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/group.ts

Complete collection endpoint refactor

---

packages/common/src/schema.ts
packages/common/src/types/database.ts
packages/common/src/types/merkle-tree.ts
packages/common/src/validation/index.ts
packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/domain/use-case/merkle-tree.ts
packages/serverless/src/model/abstract/document.ts
packages/storage/src/database/common/merkle-tree.ts

[WIP] Refactor merkle tree

---

packages/common/src/types/proof.ts
packages/compile-service/package.json
packages/compile-service/src/index.ts
packages/proof-service/src/domain/create-proof.ts
packages/serverless/src/apollo/app/metadata.ts
packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/metadata.ts
packages/serverless/src/domain/use-case/permission-security.ts
packages/serverless/src/domain/use-case/prover.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/serverless/src/domain/use-case/transaction.ts
packages/serverless/src/index.ts
packages/storage/src/database/common/merkle-tree.ts
packages/storage/src/database/global/proof.ts
packages/storage/src/database/global/rollup-history.ts
packages/storage/src/database/global/transactions.ts
packages/storage/src/database/transaction/compound-transaction-manager.ts
yarn.lock

Refactor: Prover use case

---

packages/common/src/types/common.ts
packages/common/src/types/document.ts
packages/common/src/validation/index.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/apollo/app/metadata.ts
packages/serverless/src/domain/use-case/document-history.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/permission-security.ts
packages/serverless/src/domain/utils/document.ts
packages/serverless/src/model/abstract/document.ts

Refactor: Document related endpoint take 3

---

packages/serverless/src/apollo/app/document.ts
packages/serverless/src/domain/use-case/document.ts

Update document to use new prover APIs

---

packages/proof-service/src/domain/create-proof.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/prover.ts

Bug: Fix session prover, import model and change load to getInstance merkleTree

---

packages/proof-service/src/domain/create-proof.ts
packages/serverless/src/domain/use-case/permission-security.ts

Fix: get witness and database owner code

---

packages/api/src/graphql/proof.ts
packages/common/src/types/collection.ts
packages/common/src/types/proof.ts
packages/proof-service/src/domain/create-proof.ts
packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/prover.ts
packages/storage/src/database/global/queue.ts

Refactor proof and type

---

packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/model/abstract/document.ts

Add default indexes for user created collections

---

packages/proof-service/package.json
packages/serverless/package.json
packages/storage/package.json
yarn.lock

Bug: Remove unused package conflict mongodb

---

packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/prover.ts

Fix outdated code using the old CompoundSession

---

packages/common/src/types/user.ts
packages/serverless/src/apollo/app/user.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/transaction.ts

Bug: Fix dbCreate and userMe api

---

packages/serverless/src/model/database/user-group.ts

Bug: Remove wrong unique index user group

---

packages/serverless/src/model/database/user-group.ts

Bug: Add on missing properties for add user list to group

---

packages/common/src/types/secure-storage.ts
packages/mina-service/src/service/compile-service.ts
packages/serverless/src/domain/use-case/group.ts
packages/storage/src/database/global/secure-storage.ts

Feature: Enhance checking public key from private key

---

package.json
packages/common/src/schema.ts
packages/common/src/validation/index.ts
packages/serverless/test/model/common/schema.test.ts
yarn.lock

Change UInt32 underlying type from bigint to number, add jest deps back

---

packages/serverless/src/apollo/app/document.ts

Bug: Fix wrong graphql typedef document

---

packages/mina-service/src/domain/proof.ts
packages/mina-service/src/service/task-service.ts

Fix proof task queue processing status mismatch

---

packages/common/src/types/transaction.ts
packages/serverless/src/apollo/app/transaction.ts
packages/serverless/src/domain/use-case/transaction.ts

Bug: Rename transaction submit

---

packages/mina-service/Dockerfile
packages/serverless/Dockerfile

update dockerfile for serverless and new mina-service

Devops: update dockerfile for serverless and new mina-service

---

packages/mina-service/src/service/task-service.ts

Proof service loop now backoff when error

---

packages/common/package.json
packages/common/rollup.config.js

Misc: Use rollup resolve external packages

---

packages/common/rollup.config.js
packages/serverless/rollup.config.js

Misc: Exclude resolve o1js

---

packages/mina-service/src/domain/proof.ts

Fix mongodb update misuse

---

packages/common/rollup.config.js
packages/mina-service/package.json
packages/mina-service/src/index.ts
packages/mina-service/src/service/transaction-service.ts
yarn.lock

Misc: Change node cron to queue

---

packages/storage/src/database/global/queue.ts

Fix undefined proof task due to wrong type annotation

---

packages/mina-service/src/service/compile-service.ts

Bug: Fix checking and set public key when deploy

---

packages/serverless/src/domain/use-case/transaction.ts

Bug: Fix submit transaction status

---

packages/mina-service/src/domain/proof.ts
packages/serverless/src/domain/use-case/collection.ts
packages/storage/src/database/global/queue.ts

Fix proof service using wrong mongo session & add collection creation permission check

---

packages/mina-service/src/service/transaction-service.ts

Bug: Fix add confirm to check list

---

packages/mina-service/src/service/transaction-service.ts

Misc: Filter confirming transaction status when tx not found

---

packages/serverless/package.json
packages/serverless/src/apollo/app/merkle-tree.ts
yarn.lock

Misc: Support bigint merkle tree

---

packages/serverless/src/apollo/app/merkle-tree.ts

Misc: Fix bigint param for merkle query

---

packages/common/src/types/collection.ts
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/domain/use-case/collection.ts

Bug: Fix index type conflict between graphql and serverless

---

packages/mina-service/src/domain/proof.ts
packages/mina-service/src/service/task-service.ts
packages/storage/src/database/global/queue.ts

Refactor task queue retrieval to be more robust and error prone

---

packages/common/src/types/document.ts
packages/serverless/src/apollo/app/document.ts
packages/serverless/src/domain/use-case/document.ts

Fix document history type to remove the Find postfix

---

packages/serverless/src/apollo/app/index.ts
packages/serverless/src/apollo/app/permission-ownership.ts
packages/serverless/src/apollo/index.ts

Expose permission endpoints to graphql

---

packages/common/src/types/metadata.ts
packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/metadata.ts
packages/serverless/src/domain/use-case/permission-security.ts

Bug: Fix collection metadata type

---

packages/serverless/src/domain/use-case/permission-security.ts

Fix setting permission for document and collection

---

packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/common.ts
packages/serverless/src/model/database/metadata-collection.ts

Fix collection metadata graphql type mismatch

---

packages/serverless/src/apollo/app/permission-ownership.ts
packages/serverless/src/domain/use-case/permission-security.ts

Fix set permission use PermissionBase instead of Permission

---

packages/common/src/types/group.ts
packages/serverless/src/domain/use-case/group.ts
packages/serverless/src/model/database/group.ts
packages/serverless/src/model/database/user-group.ts

Implement drop group, fix typo in groupObjectId

---

packages/common/src/types/group.ts
packages/serverless/src/apollo/app/group.ts
packages/serverless/src/domain/use-case/permission-security.ts
packages/serverless/src/model/database/user-group.ts
packages/serverless/src/model/global/user.ts

Reimplement list group by username into by user query

---

packages/mina-service/src/service/task-service.ts
packages/serverless/src/model/abstract/document.ts
packages/serverless/test/model/common/schema.test.ts
packages/storage/src/database/base/basic.ts

Disable validation when creating system index

---

packages/serverless/src/apollo/app/collection.ts
packages/serverless/src/apollo/app/common.ts

Fix collection create graphql type inconsistencies

---

packages/serverless/src/apollo/app/collection-index.ts
packages/serverless/src/domain/use-case/document.ts
packages/serverless/src/domain/use-case/index.ts
packages/serverless/src/domain/use-case/prover.ts

Fix import error

---

packages/common/src/types/collection.ts

Make schema being required on collection create type

---

packages/api/src/graphql/collection.ts
packages/common/package.json
packages/common/rollup.config.js
packages/common/src/schema.ts
packages/serverless/test/model/common/schema.test.ts
packages/zkdb/package.json
packages/zkdb/src/index.ts
packages/zkdb/src/sdk/authentication/authentication.ts
packages/zkdb/src/sdk/global/index.ts
packages/zkdb/src/sdk/global/zkdatabase-client.ts
packages/zkdb/src/sdk/helper/serialize.ts
packages/zkdb/src/sdk/implement/collection.ts
packages/zkdb/src/sdk/implement/database.ts
packages/zkdb/src/sdk/implement/document.ts
packages/zkdb/src/sdk/interfaces/collection.ts
packages/zkdb/src/test.ts

Fix document update issue and refactor schema

---

packages/smart-contract/src/common.ts
packages/smart-contract/src/compiler-cache.ts
packages/smart-contract/src/index.ts
packages/smart-contract/src/test3.ts
packages/smart-contract/src/zkdb-processor.ts
packages/smart-contract/src/zkdb-rollup.ts

Add compiler cache to speedup constructor load

---

packages/serverless/src/apollo/app/database.ts

Misc: Supported db list search by regex

---

packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/domain/use-case/merkle-tree.ts
packages/serverless/src/domain/use-case/ownership.ts

Fix transfer owner for collection/document and merkle tree endpoints using the wrong session

---

packages/zkdb/src/sdk/global/zkdatabase-client.ts
packages/zkdb/src/sdk/implement/database.ts
packages/zkdb/src/sdk/interfaces/database.ts
packages/zkdb/src/test.ts

Expose mina network as a property

---

packages/smart-contract/src/zkdb-contract.ts
packages/smart-contract/src/zkdb-processor.ts
packages/smart-contract/src/zkdb-rollup.ts
packages/smart-contract/test/rollup.test.ts

Update init method of smart contact and rollup to make it more efficient

---

packages/serverless/src/domain/use-case/collection.ts

Fix collection list not returning sizeOnDisk

---

packages/serverless/src/apollo/app/document.ts

Fix documentMerkleProofStatus outdated arguments

---

packages/api/src/graphql/client.ts
packages/api/src/graphql/collection-index.ts
packages/api/src/graphql/collection.ts
packages/api/src/graphql/common.ts
packages/api/src/graphql/database.ts
packages/api/src/graphql/document.ts
packages/api/src/graphql/group.ts
packages/api/src/graphql/merkle.ts
packages/api/src/graphql/permission-ownership.ts
packages/api/src/graphql/proof.ts
packages/api/src/graphql/rollup.ts
packages/api/src/graphql/transaction.ts
packages/api/src/graphql/user.ts
packages/api/src/utils/result.ts

Update API to use new graphql parser

---

packages/api/src/graphql/proof.ts
packages/common/src/types/proof.ts
packages/common/src/types/rollup-offchain.ts
packages/mina-service/src/domain/rollup-offchain.ts
packages/mina-service/src/service/document-worker.ts
packages/mina-service/src/service/offchain-rollup-service.ts
packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/storage/src/database/global/offchain-rollup.ts
packages/zkdb/src/sdk/implement/database.ts

Bug: Fix proof naming and fix bug after remove redundant merkleRootOld

---

.github/workflows/main.yml

Modify package list to publish

---

packages/api/package.json
packages/common/package.json
packages/permission/package.json
packages/smart-contract/package.json
packages/storage/package.json
packages/zkdb/package.json
yarn.lock

Pump dev version

---

packages/mina-service/package.json
packages/mina-service/src/helper/config.ts
packages/mina-service/src/helper/queue-worker.ts
packages/serverless/package.json
yarn.lock

Bump mina-service's dependencies to latest

---

packages/serverless/src/domain/use-case/transaction.ts

Bug: Remove checking public key since we use deploy status 

---

package.json
update-dependencies.js

Add yarn update to simplify dependency update process

---

packages/serverless/src/apollo/app/transaction.ts
packages/serverless/src/domain/use-case/transaction.ts
packages/storage/package.json
packages/storage/src/database/general/database.ts

Misc: Add on update db deploy status after user sign

---

.github/workflows/main.yml

Fix wrong package version comparison

---

packages/api/src/graphql/rollup.ts
packages/common/src/types/rollup-offchain.ts
packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/serverless/src/domain/use-case/transaction.ts
packages/zkdb/src/sdk/implement/database.ts
packages/zkdb/src/sdk/interfaces/database.ts

Feature: Add on rollup offchain state api

---

packages/mina-service/src/helper/backoff.ts
packages/serverless/src/domain/use-case/document.ts
packages/storage/src/database/common/merkle-tree.ts

Fix storage related issues

---

packages/api/package.json
packages/api/src/graphql/rollup.ts
packages/common/package.json
packages/common/src/types/transaction.ts
packages/mina-service/package.json
packages/mina-service/src/domain/rollup-offchain.ts
packages/serverless/package.json
packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/storage/package.json
packages/storage/src/database/global/onchain-rollup-history.ts
packages/zkdb/package.json
packages/zkdb/src/test.ts

…ting status for rollup onchain

Bug: Fix pagination bug, checking merkle height before db create, forgetting update api for rollup history

---

packages/mina-service/src/domain/transaction-onchain.ts
packages/zkdb/src/test.ts

Misc: Add falsy optional for failures

---

packages/serverless/src/apollo/app/document.ts

Fix documentDrop incidentally requiring a document

---

.github/workflows/build-and-push-docker.yml

Refactor GitHub Actions workflow to handle success and failure scenarios

Refactor GitHub Actions workflow to handle success and failure scenarios

---

packages/serverless/src/domain/use-case/collection.ts
packages/serverless/src/domain/use-case/rollup.ts

Bug: Prevent delete system index and hide

---

packages/serverless/src/domain/use-case/rollup.ts

Bug: Prevent create onchain rollup before deploy database

---

examples/package.json
examples/src/zk-proof.ts
examples/yarn.lock

Feature: Update example zk proof

---

packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/apollo/app/proof.ts

Fix retry failed task wrong graphql definition

---

packages/serverless/src/apollo/app/proof.ts

Fix retry failed task not working for offchain rollup

---

.github/workflows/main.yml

Add `yarn lint` at root workspace

Add yarn lint at root workspace

---

packages/serverless/src/apollo/app/merkle-tree.ts
yarn.lock

Fix eslint issue due to un-use

---

package.json
packages/api/package.json
packages/api/src/graphql/merkle.ts
packages/api/src/graphql/proof.ts
packages/common/package.json
packages/common/src/types/merkle-tree.ts
packages/common/src/types/proof.ts
packages/mina-service/package.json
packages/serverless/package.json
packages/serverless/src/apollo/app/merkle-tree.ts
packages/serverless/src/apollo/app/proof.ts
packages/storage/package.json
packages/zkdb/package.json
packages/zkdb/src/sdk/implement/database.ts
packages/zkdb/src/sdk/interfaces/database.ts
yarn.lock

Release zkdb monorepo version 1.0.2

---

.github/workflows/build-and-push-docker.yml
.github/workflows/main.yml

Add permission in github action workflow

---

examples/package.json
examples/src/zk-proof.ts
examples/yarn.lock

Update example to use zkdbb 1.3.3

---

packages/api/package.json
packages/common/package.json
packages/common/src/types/proof.ts
packages/mina-service/package.json
packages/serverless/package.json
packages/serverless/src/apollo/app/proof.ts
packages/serverless/src/apollo/app/rollup.ts
packages/storage/package.json
packages/zkdb/package.json

Feature: Add on step for zkProof

---

packages/api/package.json
packages/common/package.json
packages/common/src/types/rollup-offchain.ts
packages/mina-service/package.json
packages/serverless/package.json
packages/serverless/src/apollo/app/rollup.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/storage/package.json
packages/zkdb/package.json

Bug: Fix first failed rollup offchain state

---

packages/serverless/src/index.ts

Fix weak Content Security Policy and insecure HTTP cookie

---

packages/mina-service/src/service/compile-service.ts
packages/serverless/src/apollo/app/database.ts
packages/serverless/src/domain/use-case/database.ts
packages/serverless/src/domain/use-case/rollup.ts
packages/serverless/src/domain/use-case/transaction.ts

Bug: Fix on chain transaction undefined

---

packages/serverless/src/index.ts

Fix express-session secure cookies not being set

---

packages/serverless/src/index.ts

Allow cookies to be set in testing environments
